### ISSUE TITLE
Implement Footer 

### ISSUE THREAD

**Issue by dorelljames** [reactcebu/website-v2#21]
Based from the image below, it should have a white section showing React Cebu's logo and from down below the links which are already present in the current state of the website. Please also add the Social Media icons from the bottom right part.

![image](https://user-images.githubusercontent.com/977413/90971093-ff2b9200-e53e-11ea-8bc6-e0a108619358.png)

**Comment by clydegold8** [comment]
Hello I would like to ask if the footer should be fixed (position: fixed ) within the website?
Thanks!

**Comment by dorelljames** [comment]
Hello @clydegold8. Yes, it should be fixed at the bottom. Please also take note of the white area where we put in the logo.
